-- Tabela: analises
CREATE TABLE IF NOT EXISTS public.analises (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  filename text NOT NULL
);

-- Tabela: financeiro_cadastro_procedimentos
CREATE TABLE IF NOT EXISTS public.financeiro_cadastro_procedimentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  nome text NOT NULL,
  descricao text,
  categoria bigint,
  valor_minimo numeric,
  embedding jsonb,
  tipo text
);

-- Tabela: elementos_analises
CREATE TABLE IF NOT EXISTS public.elementos_analises (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  tipo text,
  nome text,
  freq bigint,
  custo_unit numeric,
  custo_total numeric,
  status text,
  valor_proposto numeric,
  id_gold_label bigint REFERENCES public.financeiro_cadastro_procedimentos(id),
  analise_id bigint REFERENCES public.analises(id) ON DELETE CASCADE
);

-- Habilitar RLS nas tabelas
ALTER TABLE public.analises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.elementos_analises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_cadastro_procedimentos ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para acesso público
CREATE POLICY "Permitir leitura de analises" ON public.analises
  FOR SELECT USING (true);

CREATE POLICY "Permitir inserção de analises" ON public.analises
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir leitura de elementos" ON public.elementos_analises
  FOR SELECT USING (true);

CREATE POLICY "Permitir atualização de elementos" ON public.elementos_analises
  FOR UPDATE USING (true);

CREATE POLICY "Permitir inserção de elementos" ON public.elementos_analises
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir leitura de procedimentos" ON public.financeiro_cadastro_procedimentos
  FOR SELECT USING (true);

CREATE POLICY "Permitir inserção de procedimentos" ON public.financeiro_cadastro_procedimentos
  FOR INSERT WITH CHECK (true);